CREATE TABLE CONFERENCE (
    ID INT PRIMARY KEY,
    PARTICIPANT_COUNT INT CHECK (PARTICIPANT_COUNT > 0),
    EVENT_DATE DATE CHECK (EVENT_DATE > CURRENT_DATE),
    LOCATION VARCHAR(100),
    ORGANIZER VARCHAR(50),
    TOPIC VARCHAR(100),
    DURATION FLOAT CHECK (DURATION > 0),
    STATUS VARCHAR(50) CHECK (STATUS IN ('Active', 'Planned', 'Cancelled'))
);
CREATE TABLE SPEAKER (
    ID INT PRIMARY KEY,
    CONFERENCE_ID INT REFERENCES CONFERENCE (ID),
    SPEAKER VARCHAR(100)
);
CREATE TABLE PARTICIPANT (
    ID INT PRIMARY KEY,
    CONFERENCE_ID INT REFERENCES CONFERENCE (ID),
    PARTICIPANT VARCHAR(100)
);

CREATE TABLE SUPPORTED_METHODS_API (
    ID INT PRIMARY KEY,
    API_ID INT REFERENCES API (ID),
    METHOD VARCHAR(20) CHECK (METHOD IN ('GET', 'POST', 'PUT', 'DELETE'))
);

CREATE TABLE CONFIGURATION (
    ID INT PRIMARY KEY,
    PARAMETERS VARCHAR(200),
    AUTO_UPDATE_INTERVAL INT CHECK (AUTO_UPDATE_INTERVAL > 0),
    LOCALE VARCHAR(20) CHECK (LOCALE IN ('en-US', 'uk-UA')),
    DATE_FORMAT VARCHAR(20) CHECK (DATE_FORMAT IN ('DD/MM/YYYY', 'MM/DD/YYYY')),
    TEMPERATURE_FORMAT VARCHAR(5) CHECK (TEMPERATURE_FORMAT IN ('°C', '°F'))
);
