name: SQL Schema Code Convention Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  sql-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SQLLint
      run: npm install -g sql-lint
      
    - name: Set up SQLFluff
      run: pip install sqlfluff

    - name: Run SQLFluff
      run: sqlfluff lint DataSchemaModified.sql --dialect postgres


    - name: Run SQLLint
      run: sql-lint DataSchemaModified.sql
