name: Check Data Schema Code Convention

on:
  push:
    branches:
      - main

jobs:
  check_code_convention:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install sql-lint
        run: npm install -g sql-lint

      - name: Lint SQL schema file
        run: |
          if [ -f "RelationDB_DetailedDataSchema.sql" ]; then
            if [ -f "RelationDB_DetailedDataSchema.sql" ]; then
              sql-lint RelationDB_DetailedDataSchema.sql || echo "SQL schema does not meet code conventions"
            else
              echo "RelationDB_DetailedDataSchema.sql not found"
            fi
          else
            echo "RelationDB_DetailedDataSchema.sql not found"
          fi
