name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  print_data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Установить Apache Struts
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://archive.apache.org/dist/struts/2.5.29/struts-2.5.29-all.zip -O struts.zip
          unzip struts.zip -d struts
          echo "export STRUTS_HOME=$(pwd)/struts" >> $GITHUB_ENV
          echo 'export PATH=$PATH:$STRUTS_HOME/bin' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Проверить версию Apache Struts
        run: |
          if [ -x "$(command -v struts)" ]; then
            struts -v
          else
            echo "Apache Struts не установлен"
          fi

  print_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Установить PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql

      - name: Проверить версию PostgreSQL
        run: psql --version 
