name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-data-processing-software:
    runs-on: ubuntu-latest
    steps:
      # Шаг проверки репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Установка JDK и Maven
      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      # Установка пакетов и вывод версии Apache Struts
      - name: Display Apache Struts version
        run: |
          mvn dependency:list | grep struts || echo "Struts dependency not found"

      # Вывод версии JVM (Java Virtual Machine)
      - name: Display Java (JVM) version
        run: java -version

  check-database-software:
    needs: check-data-processing-software
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Обновление и установка клиента PostgreSQL
      - name: Display PostgreSQL version
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql --version
