name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-data-processing-software:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Вывод версии Apache Struts
      - name: Display Apache Struts version
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn dependency:list | grep struts

      # Вывод версии JVM (Java Virtual Machine)
      - name: Display Java (JVM) version
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk
          java -version

  check-database-software:
    needs: check-data-processing-software
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Вывод версии PostgreSQL
      - name: Display PostgreSQL version
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql --version
