name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  print_data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Установить Apache Struts
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://archive.apache.org/dist/struts/2.5.29/struts-2.5.29-all.zip -O struts.zip
          unzip struts.zip -d struts
          if [ -d "struts" ]; then
            echo "Apache Struts установлен в папке struts"
          else
            echo "Ошибка при установке Apache Struts"
          fi

  print_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Установить PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql

      - name: Проверить версию PostgreSQL
        run: psql --version || echo "PostgreSQL не установлен"
