name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  print_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Print Apache Struts version
        run: struts -v || echo "Struts is not installed"

      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql

      - name: Print PostgreSQL version
        run: psql --version || echo "PostgreSQL is not installed"
