name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  print_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      # Проверка версии Apache Struts
      - name: Check Struts version
        run: |
          if [ -f path/to/struts-core.jar ]; then
            unzip -p path/to/struts-core.jar META-INF/MANIFEST.MF | grep 'Implementation-Version';
          else
            echo "Struts is not installed";
          fi

      # Установка PostgreSQL
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql

      # Запуск PostgreSQL
      - name: Start PostgreSQL
        run: sudo service postgresql start

      # Вывод версии PostgreSQL
      - name: Print PostgreSQL version
        run: psql --version || echo "PostgreSQL is not installed"
